/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class K_PathsWrapJNI {
  public final static native void k_paths(long jarg1, NodeVec jarg1_, long jarg2, K_Paths jarg2_, long jarg3, Node jarg3_, long jarg4, Node jarg4_, long jarg5);
}
