/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class NodeVec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NodeWrapJNI.delete_NodeVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NodeVec() {
    this(NodeWrapJNI.new_NodeVec__SWIG_0(), true);
  }

  public NodeVec(long n) {
    this(NodeWrapJNI.new_NodeVec__SWIG_1(n), true);
  }

  public long size() {
    return NodeWrapJNI.NodeVec_size(swigCPtr, this);
  }

  public long capacity() {
    return NodeWrapJNI.NodeVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    NodeWrapJNI.NodeVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return NodeWrapJNI.NodeVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    NodeWrapJNI.NodeVec_clear(swigCPtr, this);
  }

  public void add(Node x) {
    NodeWrapJNI.NodeVec_add(swigCPtr, this, Node.getCPtr(x), x);
  }

  public Node get(int i) {
    return new Node(NodeWrapJNI.NodeVec_get(swigCPtr, this, i), false);
  }

  public void set(int i, Node val) {
    NodeWrapJNI.NodeVec_set(swigCPtr, this, i, Node.getCPtr(val), val);
  }

}
