/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class NodeWrap {
  public static void reset_nodes(NodeVec nodes) {
    NodeWrapJNI.reset_nodes(NodeVec.getCPtr(nodes), nodes);
  }

}
