/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class PathVec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PathVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PathVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NodeWrapJNI.delete_PathVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PathVec() {
    this(NodeWrapJNI.new_PathVec__SWIG_0(), true);
  }

  public PathVec(long n) {
    this(NodeWrapJNI.new_PathVec__SWIG_1(n), true);
  }

  public long size() {
    return NodeWrapJNI.PathVec_size(swigCPtr, this);
  }

  public long capacity() {
    return NodeWrapJNI.PathVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    NodeWrapJNI.PathVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return NodeWrapJNI.PathVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    NodeWrapJNI.PathVec_clear(swigCPtr, this);
  }

  public void add(Node x) {
    NodeWrapJNI.PathVec_add(swigCPtr, this, Node.getCPtr(x), x);
  }

  public Node get(int i) {
    long cPtr = NodeWrapJNI.PathVec_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Node(cPtr, false);
  }

  public void set(int i, Node val) {
    NodeWrapJNI.PathVec_set(swigCPtr, this, i, Node.getCPtr(val), val);
  }

}
