/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class potential_path {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected potential_path(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(potential_path obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        YenWrapJNI.delete_potential_path(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPath(PathVec value) {
    YenWrapJNI.potential_path_path_set(swigCPtr, this, PathVec.getCPtr(value), value);
  }

  public PathVec getPath() {
    long cPtr = YenWrapJNI.potential_path_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PathVec(cPtr, false);
  }

  public void setDistance(double value) {
    YenWrapJNI.potential_path_distance_set(swigCPtr, this, value);
  }

  public double getDistance() {
    return YenWrapJNI.potential_path_distance_get(swigCPtr, this);
  }

  public potential_path() {
    this(YenWrapJNI.new_potential_path(), true);
  }

}
