/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class SmoothSortWrapJNI {
  public final static native int NUMBER_OF_LEONARDO_NUMBERS_get();
  public final static native int TREES_LENGTH_get();
  public final static native long new_SmoothsortPriorityQueue(long jarg1, NodeVec jarg1_);
  public final static native void SmoothsortPriorityQueue_sort(long jarg1, SmoothsortPriorityQueue jarg1_);
  public final static native int SmoothsortPriorityQueue_getQueueSize(long jarg1, SmoothsortPriorityQueue jarg1_);
  public final static native long SmoothsortPriorityQueue_dequeue(long jarg1, SmoothsortPriorityQueue jarg1_);
  public final static native void delete_SmoothsortPriorityQueue(long jarg1);
}
