/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.maps.android.utils.demo;

public class YenWrapJNI {
  public final static native void potential_path_path_set(long jarg1, potential_path jarg1_, long jarg2, PathVec jarg2_);
  public final static native long potential_path_path_get(long jarg1, potential_path jarg1_);
  public final static native void potential_path_distance_set(long jarg1, potential_path jarg1_, double jarg2);
  public final static native double potential_path_distance_get(long jarg1, potential_path jarg1_);
  public final static native long new_potential_path();
  public final static native void delete_potential_path(long jarg1);
  public final static native void Yen(long jarg1, NodeVec jarg1_, long jarg2, YenPath jarg2_, long jarg3, Node jarg3_, long jarg4, Node jarg4_, int jarg5);
}
