/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.patrick.wazemap;

public class AstarWrap {
  public static void Astar(NodeVec nodes, PathVec path, Node start_node, Node end_node, float h_weight, boolean debug) {
    AstarWrapJNI.Astar(NodeVec.getCPtr(nodes), nodes, PathVec.getCPtr(path), path, Node.getCPtr(start_node), start_node, Node.getCPtr(end_node), end_node, h_weight, debug);
  }

}
