/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.patrick.wazemap;

public class DijkstraWrapJNI {
  public final static native void Dijkstra(long jarg1, NodeVec jarg1_, long jarg2, PathVec jarg2_, long jarg3, Node jarg3_, long jarg4, Node jarg4_);
}
