/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.patrick.wazemap;

public class LinkedNodes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LinkedNodes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LinkedNodes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NodeWrapJNI.delete_LinkedNodes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LinkedNodes() {
    this(NodeWrapJNI.new_LinkedNodes__SWIG_0(), true);
  }

  public LinkedNodes(long n) {
    this(NodeWrapJNI.new_LinkedNodes__SWIG_1(n), true);
  }

  public long size() {
    return NodeWrapJNI.LinkedNodes_size(swigCPtr, this);
  }

  public long capacity() {
    return NodeWrapJNI.LinkedNodes_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    NodeWrapJNI.LinkedNodes_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return NodeWrapJNI.LinkedNodes_isEmpty(swigCPtr, this);
  }

  public void clear() {
    NodeWrapJNI.LinkedNodes_clear(swigCPtr, this);
  }

  public void add(Node.linkedNode x) {
    NodeWrapJNI.LinkedNodes_add(swigCPtr, this, Node.linkedNode.getCPtr(x), x);
  }

  public Node.linkedNode get(int i) {
    return new Node.linkedNode(NodeWrapJNI.LinkedNodes_get(swigCPtr, this, i), false);
  }

  public void set(int i, Node.linkedNode val) {
    NodeWrapJNI.LinkedNodes_set(swigCPtr, this, i, Node.linkedNode.getCPtr(val), val);
  }

}
