/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.patrick.wazemap;

public interface SmoothSortWrapConstants {
  public final static int NUMBER_OF_LEONARDO_NUMBERS = SmoothSortWrapJNI.NUMBER_OF_LEONARDO_NUMBERS_get();
  public final static int TREES_LENGTH = SmoothSortWrapJNI.TREES_LENGTH_get();
}
